# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli-mate" do
  desc ""
  homepage "https://github.com/yuldoshevgg/cli-mate"
  version "1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cli-mate"

  on_macos do
    url "https://github.com/yuldoshevgg/cli-mate/releases/download/v1.0/cli-mate_1.0_darwin_all.tar.gz"
    sha256 "5b4b50c9220a5e71443892e09b4fd1735ce7f168c6a262c8ac3bbcc927948a8c"
  end

  on_linux do
    on_intel do
      url "https://github.com/yuldoshevgg/cli-mate/releases/download/v1.0/cli-mate_1.0_linux_amd64.tar.gz"
      sha256 "b586395f33f1b72afa9fe26e2f7802566ca4fa594ee699a113bde79e2240ba86"
    end
    on_arm do
      url "https://github.com/yuldoshevgg/cli-mate/releases/download/v1.0/cli-mate_1.0_linux_arm64.tar.gz"
      sha256 "42adc03935f11536d65d4a8372b68bcf259d0e6bd249b8b9426edde9954a136d"
    end
  end

  # No zap stanza required
end
